name: ppd_python
channels:
   - defaults
   - conda-forge
dependencies:
   - python=3.8
   - ipython
   - jupyter
   - numpy
   - matplotlib
   - pandas
   - cartopy
   - xarray
   - netcdf4
   - seaborn
   - spyder
   - tqdm
   - scipy
   - iris
   - plotly
   - cftime
   - nc-time-axis
   - scikit-learn
